### ISSUE TITLE
prompt / historique

### ISSUE THREAD

**Issue by y-syo** [KeyZox71/ft_minipowershell#3]
Si possible custom le prompt via un fichier

![Image](https://github.com/KeyZox71/ft_minipowershell/assets/45126464/5ef77389-d850-44cd-83aa-bffe8ea68743)

**Comment by y-syo** [comment]
> get_hostname.c
tu free pas le buffer si y'a des erreurs, ça leak ça D:
a part les free du buffer c'est niquel par contre

> get_prompt.c
indentation de fou
![image](https://github.com/KeyZox71/ft_minipowershell/assets/95646468/19818a4e-5a8c-4a1c-84fd-2cc793dfcf45)

a part le buffer dans le hostname j'pense que c'est ok 👍

**Comment by KeyZox71** [comment]
Niveau custom du prompt dans un fichier trop chiant donc je le ferai si vraiment il y a le temps.

**Comment by KeyZox71** [comment]
Normalement le reste est fix
